### PR TITLE
Add Sort function

### PR DESCRIPTION
**Pull request by muhamed-amr**

### CODE REVIEW

**Review by LinaSabboula — COMMENTED** [review]
Can you print the ==== after your output so each function is clearly separated and possibly print the array in one line separated by spaces instead of each number on a new line

**Review by Mustafama7moud — DISMISSED** [review]

**Review by LinaSabboula — COMMENTED** [review]
syntax error in line 401 (printing without a new line should just be print instead of println) and at the end print an new line
theres also a missing closing bracket at the end

**Review by OmarHatem28 — APPROVED** [review]

**Comment by muhamed-amr** [comment]
I updated yesterday and it has no error ,, i am waiting for your approval !!

**Review by yosra99 — APPROVED** [review]

**Comment by muhamed-amr** [comment]
I resolved conflict, updated my code and fixed error (add break; to case 12)

**Comment by muhamed-amr** [comment]
I resolved conflict, updated my code and fixed error (add break; to case 12)

**Pull request merged**
