### PR TITLE
Adding Get The 3 Minimum Numbers and Call it in the Main

### PR DESCRIPTION
**Pull request by ayman76**

### CODE REVIEW

**Review by LinaSabboula — COMMENTED** [review]
Print function name in the isString case so it would be clear which function it is

**Review by ahmedAdel202090 — APPROVED** [review]

**Comment by LinaSabboula** [comment]
Also handle case when the size is less than 3

**Review by yosra99 — CHANGES_REQUESTED** [review]
The function name must be printed before the isString case so it will be printed in all cases.

**Review by yosra99 — APPROVED** [review]

**Comment by OmarHatem28** [comment]
resolve the conflicts in your branch and push your branch again and then merge it with master
you can resolve conflicts by pulling master

**Comment by ayman76** [comment]
i can't resolve the conflicts it was at .idea/workspace.xml , and i don't know how to remove it.
________________________________

**Pull request closed without merging**
