### PR TITLE
largest prime 

### PR DESCRIPTION
**Pull request by ahmedAdel202090**

### CODE REVIEW

**Review by LinaSabboula — CHANGES_REQUESTED** [review]
Print function name in the beginning before the isString condition so it would be clear which function it is
Handle condition when there are no prime numbers in array

**Review by yosra99 — CHANGES_REQUESTED** [review]
Print function name in the beginning before the isString condition so it would be clear which function it is

**Review by yosra99 — APPROVED** [review]

**Review by LinaSabboula — CHANGES_REQUESTED** [review]
0 is not a prime

**Comment by LinaSabboula** [comment]
Prime numbers start by 2,3,5,7,11,...... and 1 and 0 are not primes

**Comment by ahmedAdel202090** [comment]
you can check again after editing on the code and add zero conditions and the prime numbers will be only 2,3,5,...

**Review by OmarHatem28 — APPROVED** [review]

**Review by LinaSabboula — APPROVED** [review]

**Comment by OmarHatem28** [comment]
resolve the conflicts in your commit either from github or pull master and fix conflicts in your working directory then push again to your branch and merge it with master

**Pull request merged**
